### ISSUE TITLE
Redis subchart outdated

### ISSUE THREAD

**Issue by lathspell** [oauth2-proxy/manifests#108]
The current Redis subchart points to a chart which uses Redis 6.2 although their latest version is 7.0.
(I have no specific reasons to want the 7.x version, just noticed that a couple of CVEs seems to be fixed in Redis meanwhile)

See 
* https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/Chart.yaml
* https://github.com/bitnami/charts/blob/master/bitnami/redis/Chart.yaml
* https://github.com/redis/redis/releases

**Comment by pierluigilenoci** [comment]
@lathspell would you be kind enough to open a PR?

**Comment by lathspell** [comment]
https://github.com/oauth2-proxy/manifests/pull/109

**Comment by pierluigilenoci** [comment]
@lathspell thank you a lot. Your PR needs to be reworked a little.

**Comment by pierluigilenoci** [comment]
Solved by #165
