### ISSUE TITLE
Upgrade app version to 7.X

### ISSUE THREAD

**Issue by pollier** [oauth2-proxy/manifests#12]
Chart currently deploy version 5.1.1 of the app,
Looking at the main repo release manifests there is at least 2 CVE that were fixed since 5.1.1 (https://github.com/oauth2-proxy/oauth2-proxy/security/advisories/GHSA-5m6c-jp6f-2vcv & https://github.com/oauth2-proxy/oauth2-proxy/security/advisories/GHSA-4mf2-f3wh-gvf2) updating the version deployed by the chart would be nice.

I've tried just bumping the docker tag up to 6.1.1 and deployment is working on my setup (EKS 1.18) but maybe i'm missing some new parameters / syntax that appears with 6+, willing to contribute to the chart if necessary.

Thanks for amazing work :)

**Comment by SeWieland** [comment]
Yes! I'm already running this chart and am using imageTag: 7.0.1 without issues as well :)

**Comment by pollier** [comment]
I've done the change required in this PR https://github.com/oauth2-proxy/manifests/pull/18

**Comment by robin-wayve** [comment]
@desaintmartin this can now be closed I think? 🎉

**Comment by desaintmartin** [comment]
Indeed! Closing.
