### ISSUE TITLE
imagepullsecret is not getting assgned to pod or deployment

### ISSUE THREAD

**Issue by amlahoti** [oauth2-proxy/manifests#128]
We have manually deployed a pull secret so that we can connect to our private container registry, please find deployment output below and deployment and pod yaml files. The imagePullSecrets created is not getting assigned to pod 
ok: [localhost] => changed=false 
  attempts: 1
  command: /usr/local/bin/helm --version=6.7.3
  invocation:
    module_args:
      api_key: null
      atomic: false
      binary_path: null
      ca_cert: null
      chart_ref: anthos-onPrem/oauth2-proxy
      chart_repo_url: null
      chart_version: 6.7.3
      context: null
      create_namespace: true
      disable_hook: false
      force: false
      history_max: null
      host: null
      kubeconfig: /tmp/kubeconfig
      name: oauth2-proxy-delete
      purge: true
      release_name: oauth2-proxy-delete
      release_namespace: oauth2-proxy
      release_state: present
      release_values: {}
      replace: false
      skip_crds: false
      state: present
      timeout: null
      update_repo_cache: true
      validate_certs: true
      values_files:
      - /tmp/oauth2_proxy_values.yaml
      wait: true
      wait_timeout: null
  status:
    app_version: 7.4.0
    chart: oauth2-proxy-6.7.3
    name: oauth2-proxy-delete
    namespace: oauth2-proxy
    revision: '1'
    status: deployed
    updated: 2023-01-20 03:49:33.400905027 +0000 UTC
    values:
      alphaConfig:
        annotations: {}
        configData: {}
        enabled: false
        existingConfig: null
        metricsConfigData: {}
        serverConfigData: {}
      authenticatedEmailsFile:
        annotations: {}
        enabled: false
        persistence: configmap
        restrictedUserAccessKey: ''
        restricted_access: ''
        template: ''
      checkDeprecation: true
      config:
        annotations: {}
        clientID: ********************
        clientSecret: **************************
        configFile: |-
          email_domains = [ "*" ]
          provider = "oidc"
          cookie_secure = true
          cookie_samesite = "lax"
          cookie_refresh = "1h"
          cookie_expire = "4h"
          cookie_name = "_oauth2_proxy"
          set_authorization_header = true
          http_address = "0.0.0.0:4180"
          upstreams = [ "static://200" ]
          skip_provider_button = true
          whitelist_domains = "[ \".test.com\" ]"
          oidc_issuer_url = "https://id.test.com/oauth2/default"
          silence_ping_logging = true
          auth_logging = true
          redirect_url = "oauth2/callback"
          scope = "openid email profile coimemberOf offline_access"
        cookieName: ''
        cookieSecret: ***************************
        google: {}
      customLabels: {}
      deploymentAnnotations: {}
      extraArgs: {}
      extraEnv: []
      extraObjects: []
      extraVolumeMounts: []
      extraVolumes: []
      hostAlias:
        enabled: false
      htpasswdFile:
        enabled: false
        entries: {}
        existingSecret: ''
      httpScheme: http
      image:
        imagePullSecrets:
        - name: anthos-onprem-pull-secret
        pullPolicy: IfNotPresent
        repository: quay.io/oauth2-proxy/oauth2-proxy
        tag: v7.4.0
      ingress:
        enabled: false
        path: /
        pathType: ImplementationSpecific
      kubeVersion: null
      livenessProbe:
        enabled: true
        initialDelaySeconds: 0
        timeoutSeconds: 1
      metrics:
        enabled: true
        port: 44180
        service:
          appProtocol: http
        servicemonitor:
          enabled: false
          interval: 60s
          labels: {}
          namespace: ''
          prometheusInstance: default
          scrapeTimeout: 30s
      nodeSelector: {}
      podAnnotations: {}
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      podLabels: {}
      podSecurityContext: {}
      priorityClassName: ''
      proxyVarsAsSecrets: true
      readinessProbe:
        enabled: true
        initialDelaySeconds: 0
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      redis:
        enabled: false
      replicaCount: 1
      resources: {}
      securityContext:
        enabled: false
        runAsNonRoot: true
      service:
        annotations: {}
        appProtocol: http
        portNumber: 4180
        type: ClusterIP
      serviceAccount:
        annotations: {}
        automountServiceAccountToken: true
        enabled: true
        name: null
      sessionStorage:
        redis:
          clientType: standalone
          cluster:
            connectionUrls: []
          existingSecret: ''
          password: ''
          passwordKey: redis-password
          sentinel:
            connectionUrls: []
            existingSecret: ''
            masterName: ''
            password: ''
            passwordKey: redis-sentinel-password
          standalone:
            connectionUrl: ''
        type: cookie
      tolerations: []
  stderr: ''
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>

The deployment.yaml on cluster
apiVersion: v1
kind: Pod
metadata:
  name: oauth2-proxy-delete-754967f948-w4wj8
  generateName: oauth2-proxy-delete-754967f948-
  namespace: oauth2-proxy
  uid: e889c174-9bdc-4777-823e-59b1b27c20e5
  resourceVersion: '33707231'
  creationTimestamp: '2023-01-20T03:49:34Z'
  labels:
    app: oauth2-proxy
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/instance: oauth2-proxy-delete
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/version: 7.4.0
    helm.sh/chart: oauth2-proxy-6.7.3
    pod-template-hash: 754967f948
  annotations:
    checksum/config: *****************
    checksum/config-emails: ****************
    checksum/google-secret:************************
    checksum/redis-secret: ***************************
    checksum/secret: *****************************
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: oauth2-proxy-delete-754967f948
      uid: 2989d970-cb68-439c-807e-a5791538db59
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-01-20T03:49:34Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:checksum/config: {}
            f:checksum/config-emails: {}
            f:checksum/google-secret: {}
            f:checksum/redis-secret: {}
            f:checksum/secret: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:pod-template-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"2989d970-cb68-439c-807e-a5791538db59"}: {}
        f:spec:
          f:automountServiceAccountToken: {}
          f:containers:
            k:{"name":"oauth2-proxy"}:
              .: {}
              f:args: {}
              f:env:
                .: {}
                k:{"name":"OAUTH2_PROXY_CLIENT_ID"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:secretKeyRef: {}
                k:{"name":"OAUTH2_PROXY_CLIENT_SECRET"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:secretKeyRef: {}
                k:{"name":"OAUTH2_PROXY_COOKIE_SECRET"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:secretKeyRef: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:livenessProbe:
                .: {}
                f:failureThreshold: {}
                f:httpGet:
                  .: {}
                  f:path: {}
                  f:port: {}
                  f:scheme: {}
                f:periodSeconds: {}
                f:successThreshold: {}
                f:timeoutSeconds: {}
              f:name: {}
              f:ports:
                .: {}
                k:{"containerPort":4180,"protocol":"TCP"}:
                  .: {}
                  f:containerPort: {}
                  f:name: {}
                  f:protocol: {}
                k:{"containerPort":44180,"protocol":"TCP"}:
                  .: {}
                  f:containerPort: {}
                  f:name: {}
                  f:protocol: {}
              f:readinessProbe:
                .: {}
                f:failureThreshold: {}
                f:httpGet:
                  .: {}
                  f:path: {}
                  f:port: {}
                  f:scheme: {}
                f:periodSeconds: {}
                f:successThreshold: {}
                f:timeoutSeconds: {}
              f:resources: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/etc/oauth2_proxy/oauth2_proxy.cfg"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:subPath: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:serviceAccount: {}
          f:serviceAccountName: {}
          f:terminationGracePeriodSeconds: {}
          f:volumes:
            .: {}
            k:{"name":"configmain"}:
              .: {}
              f:configMap:
                .: {}
                f:defaultMode: {}
                f:name: {}
              f:name: {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2023-01-20T03:49:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.36.15.69"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      subresource: status
  selfLink: /api/v1/namespaces/oauth2-proxy/pods/oauth2-proxy-delete-754967f948-w4wj8
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-20T03:49:34Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-20T03:49:37Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-20T03:49:37Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-20T03:49:34Z'
  hostIP: 10.38.0.163
  podIP: 10.36.15.69
  podIPs:
    - ip: 10.36.15.69
  startTime: '2023-01-20T03:49:34Z'
  containerStatuses:
    - name: oauth2-proxy
      state:
        running:
          startedAt: '2023-01-20T03:49:36Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
      imageID: >-
        quay.io/oauth2-proxy/oauth2-proxy@sha256:393e63c3b924e3f78a5b592ad647417af4ea229398b7bebbbd7ef3d6181aceb5
      containerID: >-
        containerd://f3ce290db3872f0309d74b88beffdfee59e2e285aa00066701e432e18e197546
      started: true
  qosClass: BestEffort
spec:
  volumes:
    - name: configmain
      configMap:
        name: oauth2-proxy-delete
        defaultMode: 420
    - name: kube-api-access-578fj
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: oauth2-proxy
      image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
      args:
        - '--http-address=0.0.0.0:4180'
        - '--https-address=0.0.0.0:4443'
        - '--metrics-address=0.0.0.0:44180'
        - '--config=/etc/oauth2_proxy/oauth2_proxy.cfg'
      ports:
        - name: http
          containerPort: 4180
          protocol: TCP
        - name: metrics
          containerPort: 44180
          protocol: TCP
      env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-delete
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-delete
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-delete
              key: cookie-secret
      resources: {}
      volumeMounts:
        - name: configmain
          mountPath: /etc/oauth2_proxy/oauth2_proxy.cfg
          subPath: oauth2_proxy.cfg
        - name: kube-api-access-578fj
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      livenessProbe:
        httpGet:
          path: /ping
          port: http
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ping
          port: http
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: oauth2-proxy-delete
  serviceAccount: oauth2-proxy-delete
  automountServiceAccountToken: true
  nodeName: caas1-rtp-dev-wrk-05-b.cisco.com
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority

Pod definition on cluster
apiVersion: v1
kind: Pod
metadata:
  name: oauth2-proxy-delete-754967f948-w4wj8
  generateName: oauth2-proxy-delete-754967f948-
  namespace: oauth2-proxy
  uid: e889c174-9bdc-4777-823e-59b1b27c20e5
  resourceVersion: '33707231'
  creationTimestamp: '2023-01-20T03:49:34Z'
  labels:
    app: oauth2-proxy
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/instance: oauth2-proxy-delete
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/version: 7.4.0
    helm.sh/chart: oauth2-proxy-6.7.3
    pod-template-hash: 754967f948
  annotations:
    checksum/config: ******************************
    checksum/config-emails: *******************************
    checksum/google-secret: ***************************************
    checksum/redis-secret: **********************************************
    checksum/secret:**************************************
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: oauth2-proxy-delete-754967f948
      uid: 2989d970-cb68-439c-807e-a5791538db59
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-01-20T03:49:34Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:checksum/config: {}
            f:checksum/config-emails: {}
            f:checksum/google-secret: {}
            f:checksum/redis-secret: {}
            f:checksum/secret: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/part-of: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
            f:pod-template-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"2989d970-cb68-439c-807e-a5791538db59"}: {}
        f:spec:
          f:automountServiceAccountToken: {}
          f:containers:
            k:{"name":"oauth2-proxy"}:
              .: {}
              f:args: {}
              f:env:
                .: {}
                k:{"name":"OAUTH2_PROXY_CLIENT_ID"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:secretKeyRef: {}
                k:{"name":"OAUTH2_PROXY_CLIENT_SECRET"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:secretKeyRef: {}
                k:{"name":"OAUTH2_PROXY_COOKIE_SECRET"}:
                  .: {}
                  f:name: {}
                  f:valueFrom:
                    .: {}
                    f:secretKeyRef: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:livenessProbe:
                .: {}
                f:failureThreshold: {}
                f:httpGet:
                  .: {}
                  f:path: {}
                  f:port: {}
                  f:scheme: {}
                f:periodSeconds: {}
                f:successThreshold: {}
                f:timeoutSeconds: {}
              f:name: {}
              f:ports:
                .: {}
                k:{"containerPort":4180,"protocol":"TCP"}:
                  .: {}
                  f:containerPort: {}
                  f:name: {}
                  f:protocol: {}
                k:{"containerPort":44180,"protocol":"TCP"}:
                  .: {}
                  f:containerPort: {}
                  f:name: {}
                  f:protocol: {}
              f:readinessProbe:
                .: {}
                f:failureThreshold: {}
                f:httpGet:
                  .: {}
                  f:path: {}
                  f:port: {}
                  f:scheme: {}
                f:periodSeconds: {}
                f:successThreshold: {}
                f:timeoutSeconds: {}
              f:resources: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/etc/oauth2_proxy/oauth2_proxy.cfg"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:subPath: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:serviceAccount: {}
          f:serviceAccountName: {}
          f:terminationGracePeriodSeconds: {}
          f:volumes:
            .: {}
            k:{"name":"configmain"}:
              .: {}
              f:configMap:
                .: {}
                f:defaultMode: {}
                f:name: {}
              f:name: {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2023-01-20T03:49:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.36.15.69"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      subresource: status
  selfLink: /api/v1/namespaces/oauth2-proxy/pods/oauth2-proxy-delete-754967f948-w4wj8
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-20T03:49:34Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-20T03:49:37Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-20T03:49:37Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-01-20T03:49:34Z'
  hostIP: 10.38.0.163
  podIP: 10.36.15.69
  podIPs:
    - ip: 10.36.15.69
  startTime: '2023-01-20T03:49:34Z'
  containerStatuses:
    - name: oauth2-proxy
      state:
        running:
          startedAt: '2023-01-20T03:49:36Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
      imageID: >-
        quay.io/oauth2-proxy/oauth2-proxy@sha256:393e63c3b924e3f78a5b592ad647417af4ea229398b7bebbbd7ef3d6181aceb5
      containerID: >-
        containerd://f3ce290db3872f0309d74b88beffdfee59e2e285aa00066701e432e18e197546
      started: true
  qosClass: BestEffort
spec:
  volumes:
    - name: configmain
      configMap:
        name: oauth2-proxy-delete
        defaultMode: 420
    - name: kube-api-access-578fj
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: oauth2-proxy
      image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
      args:
        - '--http-address=0.0.0.0:4180'
        - '--https-address=0.0.0.0:4443'
        - '--metrics-address=0.0.0.0:44180'
        - '--config=/etc/oauth2_proxy/oauth2_proxy.cfg'
      ports:
        - name: http
          containerPort: 4180
          protocol: TCP
        - name: metrics
          containerPort: 44180
          protocol: TCP
      env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-delete
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-delete
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-delete
              key: cookie-secret
      resources: {}
      volumeMounts:
        - name: configmain
          mountPath: /etc/oauth2_proxy/oauth2_proxy.cfg
          subPath: oauth2_proxy.cfg
        - name: kube-api-access-578fj
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      livenessProbe:
        httpGet:
          path: /ping
          port: http
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /ping
          port: http
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: oauth2-proxy-delete
  serviceAccount: oauth2-proxy-delete
  automountServiceAccountToken: true
  nodeName: dev-wrk-05-b..com
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority

**Comment by pierluigilenoci** [comment]
@amlahoti could you please format your request in a better way because is unreadable?

**Comment by pierluigilenoci** [comment]
Regardless of the formatting, the configuration to do what you need is this:
https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/templates/deployment.yaml#L322-L323
What parameters pass to the helm chart?

**Comment by pierluigilenoci** [comment]
It was closed due to lack of feedback from the reporter.
