### ISSUE TITLE
htpasswd-file template should be renamed to reflect the type of k8s resource it creates

### ISSUE THREAD

**Issue by aiciobanu** [oauth2-proxy/manifests#13]
`configmap-htpasswd-file.yaml` name states that the k8s resource will be of type `ConfigMap`

## Expected Behavior
The name of the template should reflect the k8s resource type it creates

## Current Behavior
The name suggests that a `ConfigMap` will be created, but instead it creates a `Secret` -> https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/templates/configmap-htpasswd-file.yaml#L3

## Possible Solution
Rename the template to `secret-htpasswd-file.yaml`

**Comment by pierluigilenoci** [comment]
@aiciobanu would you like to do a PR to solve?

**Comment by morganchristiansson** [comment]
htpasswd contains password hashes so secret is probably correct type for it

**Comment by pierluigilenoci** [comment]
@aiciobanu is this still a problem for you?

**Comment by pierluigilenoci** [comment]
@aiciobanu so?
