### ISSUE TITLE
wrong type for value; expected string; got bool

### ISSUE THREAD

**Issue by michalsabol2** [oauth2-proxy/manifests#133]
Hello,
for setting>       `--set extraArgs.set-authorization-header="true" `
there is an error:
```
Error: template: oauth2-proxy/templates/deployment.yaml:76:32: executing "oauth2-proxy/templates/deployment.yaml" at <$value>: wrong type for value; expected string; got bool
```
for chart version 6.9.0 (6.8.0 works fine)

Have a nice day

**Comment by jkroepke** [comment]
@michalsabol2

The currently workaround would be --set-string instead using --set 

`--set-string extraArgs.set-authorization-header="true"`

**Comment by michalsabol2** [comment]
It works,
thank you
