### ISSUE TITLE
Can we have the revisionHistoryLimit as a configurable value of the helm chart?

### ISSUE THREAD

**Issue by atringle** [oauth2-proxy/manifests#136]
## Expected Behavior

We should be able to set the revisionHistoryLimit in our values file for a helm deployment of oauth2-proxy

![image](https://user-images.githubusercontent.com/99745711/222776067-9e0b4ed6-8606-420d-a525-874c57bc0df6.png)

## Current Behavior

There is no value for setting the revision history limit in the value file

## Possible Solution

Allow setting the revisionHistoryLimitValue in the values file and if not specified use the default
I think something like this would work in the deployment.yaml file of the helm chart

```helm
{{- if .Values.revisionHistoryLimit}}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
{{- end }}
```
![image](https://user-images.githubusercontent.com/99745711/222778032-a7b46405-1446-4432-a5b5-3dbaca7c7fe9.png)

## Context

Its important to be able to control how many old Replica Sets are maintained.

**Comment by JoelSpeed** [comment]
I've transferred this to the manifests repo since it has separate owners
