### ISSUE TITLE
Helm Error Adding Repo - Not a Valid Chart Repository or Cannot Be Reached

### ISSUE THREAD

**Issue by rye-freedom** [oauth2-proxy/manifests#14]
I would like to use this helm chart as it seems to be the official chart for oauth2-proxy. When attempting to add the oauth2-proxy repo as described in the README, the following error occurs: `Error: looks like "https://oauth2-proxy.github.io/manifests" is not a valid chart repository or cannot be reached: Get "https://oauth2-proxy.github.io/manifests/index.yaml": tls: first record does not look like a TLS handshake`.

```sh
$  helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests
Error: looks like "https://oauth2-proxy.github.io/manifests" is not a valid chart repository or cannot be reached: Get "https://oauth2-proxy.github.io/manifests/index.yaml": tls: first record does not look like a TLS handshake
```

Helm Version:
```sh
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

**Comment by SeWieland** [comment]
Are you sure there is no firewall blocking the request?
```
$ helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests
"oauth2-proxy" has been added to your repositories
```

You can as well check that it is a valid repository by appending `/index.yaml` to the URL. That is everything what is required according to the [docs](https://helm.sh/docs/topics/chart_repository/#the-chart-repository-structure)

=> https://oauth2-proxy.github.io/manifests/index.yaml works fine for me

**Comment by rye-freedom** [comment]
I'm pretty sure firewall isn't an issue. I have many other repos added without issue.

```sh
$ helm repo list
NAME                	URL                                       
bitnami             	https://charts.bitnami.com/bitnami        
ingress-nginx       	https://kubernetes.github.io/ingress-nginx
runix               	https://helm.runix.net/                   
autoscaler          	https://kubernetes.github.io/autoscaler   
kubernetes-dashboard	https://kubernetes.github.io/dashboard/   
jetstack            	https://charts.jetstack.io                
stable              	https://charts.helm.sh/stable
```


This is also what I am seeing when navigating to [https://oauth2-proxy.github.io/manifests/index.yaml ](https://oauth2-proxy.github.io/manifests/index.yaml )

![image](https://user-images.githubusercontent.com/42525515/108232351-aebd7780-7110-11eb-81a2-4f05f3b3c8c9.png)

**Comment by SeWieland** [comment]
That is a very strange SSL issue, because <oauth2-proxy.github.io> is part of the github.com certificate itself (secures all DNS-records for *.github.io as well) and you can obviously establish a SSL connection to github.com.
So IMHO this seems to be related to you local setup somehow (proxy issues?).. Are you able to access the URL from a different device in another network?

**Comment by rye-freedom** [comment]
Yes that is what I figured as well. I just tried accessing on my personal computer which for sure doesn't have any proxy or firewall configs that would block, and same issue, both adding the repo to helm and accessing the [index.yaml](https://oauth2-proxy.github.io/manifests/index.yaml) page.

```sh
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}

$ helm repo add oauth2-proxy https://oauth2-proxy.github.io/manifests
Error: looks like "https://oauth2-proxy.github.io/manifests" is not a valid chart repository or cannot be reached: Get "https://oauth2-proxy.github.io/manifests/index.yaml": tls: first record does not look like a TLS handshake
```

![image](https://user-images.githubusercontent.com/42525515/108242116-8cc8f280-711a-11eb-9a29-28b9f43ab6b2.png)

**Comment by rye-freedom** [comment]
Just wanted to follow up on this. I got this working. The issue was actually with my ISP provided gateway (Xfinity) and their "Advanced Security" setting. Haven't had an issue up until now. As soon as I disabled this setting on the gateway, everything worked as it should. Sorry for the trouble and thanks for the quick response and help!

Closing with this comment.
