### ISSUE TITLE
Question: nodeSelector for redis sub-chart

### ISSUE THREAD

**Issue by LucaCre** [oauth2-proxy/manifests#146]
Hi everyone,
We have a deployment on a specific nodepool. Oauth2-proxy we can deploy with the recommended annotation from values.yml without problems to this pool. But I don't understand how to deploy redis-subchart to the specific node. We tried the following annotation without success.
'''
# Enables and configure the automatic deployment of the redis subchart
redis:
  # provision an instance of the redis sub-chart
  enabled: true
  redisPort: 6380
  replica:
    replicaCount: 0

  ### for own nodepool
  # Tolerations for pod assignment
  # Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "mynodepool"
    effect: "NoSchedule"

  # Node labels for pod assignment
  # Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector:
    role: "mynodepool"
  ###
'''

can anyone help us in this case ?
many thanks

**Comment by pierluigilenoci** [comment]
At this moment, we use the Redis chart maintained by `Bitnami.`
 
Specifically, this version:
https://github.com/bitnami/charts/pull/11019
https://github.com/bitnami/charts/blob/d4dba2b393167d79b8c8f65b46c48b70ee3a9662/bitnami/redis/

According to the values.yaml file of this version (https://github.com/bitnami/charts/blob/d4dba2b393167d79b8c8f65b46c48b70ee3a9662/bitnami/redis/values.yaml) you have to use these parameters to add the `annotations`:
https://github.com/bitnami/charts/blob/d4dba2b393167d79b8c8f65b46c48b70ee3a9662/bitnami/redis/values.yaml#L40

If you want to use `NodeSelectors` and `Tolerations` instead:

* Master
https://github.com/bitnami/charts/blob/d4dba2b393167d79b8c8f65b46c48b70ee3a9662/bitnami/redis/values.yaml#L342
https://github.com/bitnami/charts/blob/d4dba2b393167d79b8c8f65b46c48b70ee3a9662/bitnami/redis/values.yaml#L346

* Replica
https://github.com/bitnami/charts/blob/d4dba2b393167d79b8c8f65b46c48b70ee3a9662/bitnami/redis/values.yaml#L724
https://github.com/bitnami/charts/blob/d4dba2b393167d79b8c8f65b46c48b70ee3a9662/bitnami/redis/values.yaml#L728

**Comment by LucaCre** [comment]
Thank you very much, problem solved.
