### ISSUE TITLE
Working Redis configuration

### ISSUE THREAD

**Issue by DevSecNinja** [oauth2-proxy/manifests#154]
Hello,

I was hoping if anyone could share a working Redis configuration with the Helm chart. I have tried various configs but eventually I keep getting this error:

```
    # [2023/07/03 14:00:15] [main.go:54] invalid configuration:
    # unable to set a redis initialization key: dial tcp 10.43.57.255:6379: connect: operation not permitted
    # unable to delete the redis initialization key: dial tcp 10.43.57.255:6379: connect: operation not permitted
```

See my configuration here: https://github.com/DevSecNinja/k3s-home/blob/989ad31a8c1a781154be356dcfc3c37f7dca246a/kubernetes/apps/security/oauth2-proxy/app/helmrelease.yaml#L92C1-L106C1

Thank you!

**Comment by pierluigilenoci** [comment]
```yaml
redis:
  enabled: true
sessionStorage:
  type: redis
  redis:
    password: "XXXXXXX"
```

**Comment by DevSecNinja** [comment]
Thanks @pierluigilenoci, in that case it's not the config but something else going wrong. Not sure what. 

```
$ kubectl -n security logs oauth2-proxy-6cfd5bdfd7-p7nx8
[2023/07/05 19:29:54] [main.go:54] invalid configuration:
  unable to set a redis initialization key: dial tcp 10.43.86.62:6379: connect: operation not permitted
  unable to delete the redis initialization key: dial tcp 10.43.86.62:6379: connect: operation not permitted
```

The pod logs changed after that and I was lucky to catch it:

```
$ kubectl -n security logs oauth2-proxy-6cfd5bdfd7-p7nx8
[2023/07/05 19:30:35] [main.go:54] invalid configuration:
  unable to set a redis initialization key: WRONGPASS invalid username-password pair or user is disabled.
  unable to delete the redis initialization key: WRONGPASS invalid username-password pair or user is disabled.
```

Seems this has been raised before: https://github.com/oauth2-proxy/oauth2-proxy/issues/1907

**Comment by pierluigilenoci** [comment]
@DevSecNinja I suggest checking the password because that is probably the problem.

**Comment by DevSecNinja** [comment]
Thanks @pierluigilenoci - I did double check that. For now I switched to GitHub auth and will troubleshoot Azure AD with Redis later. I'll try to reduce the token size as well. Thanks!

**Comment by DreamingRaven** [comment]
For anyone who happens to stumble upon this. 
I solved this issue by removing special characters from the password!

One or the other (o2p or redis) silently does not take special chars, I can't say which, but setting the password in an existing secret from one that has special chars to one without solved it in my cluster.

**Comment by DevSecNinja** [comment]
Aaah, thanks for sharing @DreamingRaven! I'll give it a try in the future!

**Comment by DreamingRaven** [comment]
@DevSecNinja As an aside for when you do try it, I am using the Bitnami helm chart, and to answer your other question about a specific config for redis, this is my [bitnami version](https://bitnami.com/stack/oauth2-proxy/helm) values for oauth2 (please de-indent if you do copy paste):

```yaml

    enabled: true
    ingress:
      enabled: false
    redis:
      auth:
        enabled: true
        sentinel: false
        existingSecret: redis-creds
        existingSecretPasswordKey: redis-password

```
Cheers :+1:
