### ISSUE TITLE
`useApplicationDefaultCredentials` upstream feature has not merged.

### ISSUE THREAD

**Issue by rhass** [oauth2-proxy/manifests#161]
The `--google-use-application-default-credentials=true` option has not merged as of yet.

https://github.com/oauth2-proxy/oauth2-proxy/pull/2126

As result, deployments fail which do not have `useApplicationDefaultCredentials: true` configured.

**Comment by pierluigilenoci** [comment]
@rhass I know, but unfortunately, it is not in my power to push the advancement of PR to the other side.
I suggest using the option once the other PR is merged.

When the two PRs (#127 e https://github.com/oauth2-proxy/oauth2-proxy/pull/2126) were created, I hoped they would close almost simultaneously, and therefore, I approved the one on this side probably too quickly.

In the meantime, we can ask @kvanzuijlen to follow up on the open PR to close it as soon as possible.
If you think it's a good idea, you can even offer to help close the PR or create another one to develop the feature independently in the hope of having a faster approval process.

**Comment by kvanzuijlen** [comment]
@pierluigilenoci I'm in contact with @JoelSpeed about it. I'll try to get it merged asap.

**Comment by pierluigilenoci** [comment]
[#212](https://github.com/oauth2-proxy/oauth2-proxy/pull/2126) finally merged.
