### ISSUE TITLE
Wait-for-redis cannot handle redis in deployment mode

### ISSUE THREAD

**Issue by Pionerd** [oauth2-proxy/manifests#182]
The `wait-for-redis` container checks for the redis-master container to be ready, but the name of the container is semi-hardcoded as `pod/{{ include "oauth2-proxy.redis.fullname" . }}-master-0` (https://github.com/oauth2-proxy/manifests/blob/0bdde21382538e65b6c9896858fdbf7f986464d4/helm/oauth2-proxy/templates/deployment.yaml#L69C34-L69C34). This is the format of a StatefulSet. 

We would like to use redis for the sole purpose of saving the cookies, but don't mind if they get lost when redis would be restarted or killed, so we prefer to run stateless without PV, so we could run redis-master in deployment mode. This results in a pod named `oauth2-proxy-redis-master-{uuid}`, so the current check does not pass. 

As I understand, it's not possible to use a kubectl wait on a service, so we will need to determine the name of the pod to check differently.

Before writing a pull request, what do you guys think of `kubectl -n oauth2-proxy wait --for=condition=ready --selector=app.kubernetes.io/name=redis --selector=app.kubernetes.io/component=master po`? Where we could make the selectors configurable?

**Comment by pierluigilenoci** [comment]
I would say that being able to control the readiness status of the pod via selectors is certainly an evolution of the current solution, as it could lead to unwanted results if someone abuses the labels used. 🤷🏻‍♂️ 

So, I would say it all depends on how the solution is implemented. 👍🏻

**Comment by Pionerd** [comment]
It depends a bit a bit on how far we want to go. In my case (using the reds sub chart) the selector for the service is: 
```
app.kubernetes.io/component: master        # Hardcoded in redis subchart                                                                                                                                                                                         
app.kubernetes.io/instance: oauth2-proxy  # {{ .Release.Name }}                                                                                                                                                                                           app.kubernetes.io/name: redis                      # subchart name 
```
I think we could generate the above as the default selectors with the possibility of overwriting this via `values.yaml`.

**Comment by mvalenzisi** [comment]
I agree with the solution proposed, but how can we handle the case when Redis is installed with Sentinel?
In that case, the pods have the name `oauth2-proxy-redis-node-<n>` and labels:
```
app.kubernetes.io/component=node
app.kubernetes.io/instance=oauth2-proxy
app.kubernetes.io/name=redis
```

**Comment by Pionerd** [comment]
The more I think about it, the more I have the feeling that the `wait-for-redis` container should try to make an actual connection to the Redis Cluster, based on the already available connection details, instead of relying on `kubectl`.

**Comment by Pionerd** [comment]
Please let me know how to proceed. I can create a PR either for
1. Improving the `kubectl wait` with the correct pod selectors as discussed above
2. As per my last suggestion, implement something like https://github.com/mriedmann/humhub-docker/blob/c745d5db3b3012548e2514645fe47609557eb1c9/docker-entrypoint.sh#L69

**Comment by pierluigilenoci** [comment]
@Pionerd sorry for the delay in the answer. Please feel free to open a PR to address this.

**Comment by pierluigilenoci** [comment]
@Pionerd, did you find a little time to create a PR?

**Comment by Pionerd** [comment]
Not yet, but I will, apologies for the delay.

**Comment by andreas-geissler** [comment]
Just as a comment.
I recently implemented a extention for the "Readiness" check comtainer we use in ONAP.
https://github.com/onap/oom-readiness
This support the functionality to check the readiness of a service, by searching for the pod, which implements the service and check for the readiness of the Statefulset/Deployment/... 
Maybe this could help you...

**Comment by mvalenzisi** [comment]
@Pionerd 
I'm testing your fix but the init container fails with the error `Redis configuration not specified.`.
I see that `check-redis.sh` is checking some env vars, in my case I would expect `$OAUTH2_PROXY_REDIS_USE_SENTINEL` to be true.
The pod `oauth2-proxy` has indeed the correct value for that var:
```
    Environment:
      OAUTH2_PROXY_CLIENT_ID:                       <set to the key 'client-id' in secret 'oauth2-proxy'>      Optional: false
      OAUTH2_PROXY_CLIENT_SECRET:                   <set to the key 'client-secret' in secret 'oauth2-proxy'>  Optional: false
      OAUTH2_PROXY_COOKIE_SECRET:                   <set to the key 'cookie-secret' in secret 'oauth2-proxy'>  Optional: false
      OAUTH2_PROXY_SESSION_STORE_TYPE:              redis
      OAUTH2_PROXY_REDIS_PASSWORD:                  <set to the key 'redis-password' in secret 'redis-secret'>  Optional: false
      OAUTH2_PROXY_REDIS_USE_SENTINEL:              true
      OAUTH2_PROXY_REDIS_SENTINEL_MASTER_NAME:      master
      OAUTH2_PROXY_REDIS_SENTINEL_CONNECTION_URLS:  redis://oauth2-proxy-redis-headless.kube-infrastructure:26379
      OAUTH2_PROXY_REDIS_SENTINEL_PASSWORD:         <set to the key 'redis-password' in secret 'redis-secret'>  Optional: false
```
but the init container `wait-for-redis` does not:
```
    Environment:
      TOTAL_RETRY_TIME:                             180
      OAUTH2_PROXY_REDIS_SENTINEL_CONNECTION_URLS:  redis://oauth2-proxy-redis-headless.kube-infrastructure:26379
```

**Comment by mvalenzisi** [comment]
It works, thank you!
