### ISSUE TITLE
Publish helm charts also as an OCI package (e.g. on GHCR registry)

### ISSUE THREAD

**Issue by mkilchhofer** [oauth2-proxy/manifests#187]
The helm charts are published using the classic approach with a static webserver and an index.yaml.
In helm 3.8+ the OCI method went GA:
- https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html?m=1
- https://helm.sh/docs/topics/registries/
- https://github.com/helm/helm/releases/tag/v3.8.0

I see two options to use as an OCI mirror:
- GHCR (Github packages)
  You need to think about the Github organizational plan. On free plan there are 500MB included
- Quay.io (where you also push the container images)

**Comment by mkilchhofer** [comment]
> Is #181 solving your issue?

Yes :) 👍

**Comment by mkilchhofer** [comment]
Hi @pierluigilenoci 

I reopened this issue as the latest 7.0.0 didn't arrive here: https://github.com/orgs/oauth2-proxy/packages.

Maybe you could have a look if packages are public inside the Org settings:
![image](https://github.com/oauth2-proxy/manifests/assets/7290987/a29b1938-4b9d-4418-bd7c-b9ada5e461d5)

Cheers, Marco

**Comment by pierluigilenoci** [comment]
@mkilchhofer unfortunately, you are right; packages are private. 😢 

However, I do not have the permission to change this configuration. 🤷🏻‍♂️ 

I necessarily have to disturb @JoelSpeed or @NickMeves. Can you solve it? 🙏🏻

**Comment by pierluigilenoci** [comment]
@JoelSpeed or @NickMeves, can we get your attention here?

**Comment by JoelSpeed** [comment]
I believe I've changed the settings on the chart so that it should now be publicly visible, can you verify that for me?

**Comment by mkilchhofer** [comment]
> I believe I've changed the settings on the chart so that it should now be publicly visible, can you verify that for me?

Thank you @JoelSpeed, it works now! 🙏 

```bash
$ helm dep up
Getting updates for unmanaged Helm repositories...
(...)
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
(...)
Downloading oauth2-proxy from repo oci://ghcr.io/oauth2-proxy/charts
Pulled: ghcr.io/oauth2-proxy/charts/oauth2-proxy:7.4.1
Digest: sha256:998f838e24aee9f76432920efcfb8bd55ad1c6eb010d6e6483e70722ffd033cc
Deleting outdated charts
```
