### ISSUE TITLE
Defining CA file for Redis connections

### ISSUE THREAD

**Issue by BitForger** [oauth2-proxy/manifests#209]
Hi,
I'm trying to figure out if there is a way to get a CA file into the proxy instance so that it can use it to verify TLS with my hosted Redis instance. Is this possible, and if so, how would I do that?

**Comment by pierluigilenoci** [comment]
Hi @BitForger,
I want to understand precisely how you want to achieve this. 

Still, indeed, any file can be loaded into the proxy container using, for example, [volume mounting](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml#L192-L199), via a [sidecar](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml#L202-L204) and you can load any [extra manifests you want](https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml#L439).
Of course, the sidecar can also be used to take the tests you need.

Is the answer sufficient for your needs?

**Comment by BitForger** [comment]
@pierluigilenoci thanks! I think that answers the question. I'm not really picky on how it gets to the proxy, just that it gets there. So it could be mounting via sidecar or through a k8s secret. I have the file or the base64 encoded version of the file.

**Comment by pierluigilenoci** [comment]
Issue closed because doubts have been satisfied. 🚀
