### ISSUE TITLE
When a user accesses a protected service, the other sessions get invalidated

### ISSUE THREAD

**Issue by afabiani** [oauth2-proxy/manifests#219]
So far I'm experiencing an odd behavior with OAuth2-Proxy - K8 - Keycloack.
I am protecting a service through the oauth2-proxy auth endpoint.
So far it works well, however if another user connects to the same service the previous session gets invalidated and there's no way to recover it unless I manually hit the endpoint `/oauth2/start?rd=<service_endpoint>`. By doing this, again, the other session or token expires (it is not clear what's going on, no useful logs can be retreived from the oauth2-proxy pod... just a "500 Internal Server Error" on the protected endpoint).

**Comment by pierluigilenoci** [comment]
@afabiani This is the repository where the Helm chart for installing OAuth2-Proxy is maintained.
So there are better places to ask. 
Please ask in the [software's repository](https://github.com/oauth2-proxy/oauth2-proxy/issues).

So, can I close this issue?

**Comment by afabiani** [comment]
@pierluigilenoci sure thanks
