### ISSUE TITLE
Membership for @desaintmartin

### ISSUE THREAD

**Issue by desaintmartin** [oauth2-proxy/manifests#23]
Hey guys,
Could you add me to the project so that I can review some PRs?
Thanks!

**Comment by pierluigilenoci** [comment]
@erkannt could you please take a look?

**Comment by erkannt** [comment]
I am not an owner of the repo, so I can't change any settings regarding this.

@JoelSpeed can you please take a look? Maybe something to add to the readme on how to contribute/who to contact?

**Comment by JoelSpeed** [comment]
I think this is done now?

**Comment by desaintmartin** [comment]
Indeed, thanks to https://github.com/oauth2-proxy/manifests/pull/22! Closing.
