### ISSUE TITLE
Not published to https://artifacthub.io

### ISSUE THREAD

**Issue by lathspell** [oauth2-proxy/manifests#24]
If I go to https://helm.sh and click on Charts, it leads me to Artifacthub where I cannot find the Helm chart from this repo, only one from "k8s@home" which has at least some stars. 
(try https://artifacthub.io/packages/search?page=1&ts_query_web=oauth2+proxy&kind=0)

Is there a reason why this chart is not available there?

**Comment by pierluigilenoci** [comment]
@erkannt could you please take a look?

**Comment by erkannt** [comment]
Neither a dev or owner of oauth2 :]

@joelspeed I think this would be a good thing to do. The communication by Helm is that with the EOL for helm/stable they see Artifacthub as the place for helm charts to be discovered.

There are some steps to get the Chart marked as _verified_ and _official_. I don't think I can really help with this, as it ideally needs to be done by the 'owners' of the package.

**Comment by JoelSpeed** [comment]
Yeah this seems like a reasonable thing to do, not sure if I'll have time in the near future but perhaps one of the other @oauth2-proxy/manifest-maintainers will

**Comment by desaintmartin** [comment]
Pushed artifacthub-repo.yml to gh-pages.

**Comment by desaintmartin** [comment]
![Screenshot 2021-05-28 at 08 37 13](https://user-images.githubusercontent.com/38929/119940759-efd6ea80-bf8f-11eb-9e9b-01a9afcdf109.png)
