### ISSUE TITLE
404 https://oauth2-proxy.github.io/manifests

### ISSUE THREAD

**Issue by krisero** [oauth2-proxy/manifests#252]
Hi,
I am getting a 404 status code when trying to access `https://oauth2-proxy.github.io/manifests`. Is it temporary?

**Comment by viallikavoo** [comment]
I am getting this too. Seems like it is related to :
https://github.com/oauth2-proxy/manifests/actions/runs/11794657444/job/32852738030

**Comment by kaufmo** [comment]
it seems that the gh-pages branch is deleted therefore the registry is not available anymore

**Comment by pierluigilenoci** [comment]
I tried to reenable it, but I don't know if this is the expected result. 😢

**Comment by pierluigilenoci** [comment]
@erkannt @JoelSpeed, could you please take a look?

**Comment by HotThoughts** [comment]
This repository works: oci://ghcr.io/oauth2-proxy/charts

**Comment by swbsf** [comment]
Error: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aoauth2-proxy%2Fcharts%3Apull&service=ghcr.io: 403 Forbidden]

But it does not seem public?

**Comment by user-45-20** [comment]
Using `oci://ghcr.io/oauth2-proxy/charts` as a workaround does not for me using the latest available Helm (v3.16.2):

```
Error: looks like "oci://ghcr.io/oauth2-proxy/charts" is not a valid chart repository or cannot be reached: object required
```

**Comment by khartahk** [comment]
Theres a bug in the updated README.md file: https://github.com/oauth2-proxy/manifests/actions/runs/11795337858/job/32854843699#step:4:13

```
     Liquid Warning: Liquid syntax error (line 296): [:dot, "."] is not a valid expression in "{{ .Values.tplValue }}" in helm/oauth2-proxy/README.md
    Liquid Warning: Liquid syntax error (line 334): [:dot, "."] is not a valid expression in "{{.StatusCode}}" in helm/oauth2-proxy/README.md```

The pipeline should have probably failed.

**Comment by jaakkom** [comment]
I am having same issue.

**Comment by Moglum** [comment]
The OCI registry works just fine

```shell
helm template oauth2proxy-test oci://ghcr.io/oauth2-proxy/charts/oauth2-proxy --version 7.7.29
```

**Comment by neilharris123** [comment]
> The OCI registry works just fine
> 
> ```shell
> helm template oauth2proxy-test oci://ghcr.io/oauth2-proxy/charts/oauth2-proxy --version 7.7.29
> ```

This won't necessarily work for everyone, people using older versions of helm in their pipelines/tools may have issues querying for OCI tags.

**Comment by tuunit** [comment]
I'm looking into now.

**Comment by tuunit** [comment]
Issue has been resolved!
