### ISSUE TITLE
Upgrade redis subchart to the latest version

### ISSUE THREAD

**Issue by pierluigilenoci** [oauth2-proxy/manifests#26]
Now the chart uses a really old Redis chart. Could be nice to upgrade it to the latest version. Thanks.

**Comment by pierluigilenoci** [comment]
@erkannt could you please take a look?

**Comment by WorkAlexGahr** [comment]
Dear all is there any possibility of a progress on this? 
Seems the current redis SubChart has issues when we set a password.

auth:
  password: ""
  existingSecret: ""
  existingSecretPasswordKey: ""

Seems the redis subchart also renders incorrect when we set a pwd on a local mashine.
The new charts for redis render without issues.

**Comment by pierluigilenoci** [comment]
@WorkAlexGahr I tried to prepare a PR in the past (https://github.com/oauth2-proxy/manifests/pull/34) but I didn't find the time to finish it. 😞 

Feel free to open a new one but please read all the comments in the previous one. 👍🏻

**Comment by pierluigilenoci** [comment]
Fixed with https://github.com/oauth2-proxy/manifests/pull/79
