### ISSUE TITLE
Route requests to sidecar container first

### ISSUE THREAD

**Issue by edorizzardi** [oauth2-proxy/manifests#272]
In my organization, we require to route requests to oauth2proxy to its sidecar container first. At the moment, is not possible to achieve this with the helm chart, since the service's targetPort is by default `httpSchema`. I propose some non-breaking changes to allow for this scenario, introducing the new `.Values.service.targetPort`.

Pull request: https://github.com/oauth2-proxy/manifests/pull/270

**Comment by pierluigilenoci** [comment]
Thank you for your contribution. 🚀
