### ISSUE TITLE
TLS doc error

### ISSUE THREAD

**Issue by holmesb** [oauth2-proxy/manifests#38]
Hi,

[TLS documentation](https://github.com/oauth2-proxy/manifests/blob/9b075555cb1dba81738d2bf811ce3aa7bb1c4bcd/helm/oauth2-proxy/README.md#tls-configuration) has wrong tls key names.  Should be [tls-cert-file and tls-key-file](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/tls/), not tls-cert and tls-key.

**Comment by pierluigilenoci** [comment]
@holmesb would you like to do a PR to solve?

**Comment by pierluigilenoci** [comment]
@holmesb is this still a problem for you?

**Comment by pierluigilenoci** [comment]
@holmesb so?

**Comment by pierluigilenoci** [comment]
@holmesb any news on this?

**Comment by pierluigilenoci** [comment]
Fixed with #50
