### ISSUE TITLE
Extend configuration for "configaccesslist" under the key "restricted_user_access"

### ISSUE THREAD

**Issue by morarucostel** [oauth2-proxy/manifests#44]
**Problem:**
When using the authenticatedEmailsFile's configaccesslist option stored either as a configmap or a secret, the key under which the values are stored is hard coded to `restricted_user_access`. 
Applications that is already built and uses another key to store the email list can not access the values. 

**Solution:**
Configure the key `restricted_user_access` in the deployment and in the configmap/secret to be retrieved from the values. 
The default value should still be `restricted_user_access` for backward compatibility, however if the end user wants to change it, the chart can allow it through a new property in the values.

**Comment by morarucostel** [comment]
The change is quite minor, will not take too much to change the helm chart. 
I can push a PR in the next days.

**Comment by pierluigilenoci** [comment]
@morarucostel can this ticket be closed now?

**Comment by pierluigilenoci** [comment]
@morarucostel so?

**Comment by pierluigilenoci** [comment]
Closed with #45
