### ISSUE TITLE
ConfigMap for --custom-templates-dir?

### ISSUE THREAD

**Issue by lathspell** [oauth2-proxy/manifests#47]
oauth2-proxy has the cli option `--custom-templates-dir` to set the name of a directory in which the HTML templates for e.g. the error page is.

In Kubernetes this would probably be solved using a config map with one entry per HTML file which is mappted into a folder.

This does need some support from the Helm chart though. Probably similar to `configmap-authenticated-emails-file.yaml`.

**Comment by pierluigilenoci** [comment]
Would you be kind enough to do a PR?

**Comment by u-phoria** [comment]
In case it helps anyone, I was able to achieve something similar by making use of `extraVolumes` / `extraVolumeMounts` to mount a pre-created `configMap` with file content, as suggested.

This then allowed standard `configFile` settings such as `custom_sign_in_logo` to reference mounted content. Should work for custom sign-in and error pages via `custom_templates_dir` too.

**Comment by pierluigilenoci** [comment]
@lathspell is this still a problem for you?

**Comment by lathspell** [comment]
@u-phoria 's solution sounds like a good workaround

**Comment by pierluigilenoci** [comment]
@lathspell so how do we want to continue?

**Comment by pierluigilenoci** [comment]
@lathspell so?

**Comment by lathspell** [comment]
u-phoria's solution is fine for me, you can close the issue.
