### ISSUE TITLE
Ingress has wrong API version with k8s 1.19

### ISSUE THREAD

**Issue by czunker** [oauth2-proxy/manifests#51]
Applying chart version 4.1.0 on k8s 1.19 results in the wrong API version for the Ingress object:
```
extensions/v1beta1
```
instead of
```
networking.k8s.io/v1
```

With chart version 4.0.2 it works as expected.

This is the commit which changed the behavior: https://github.com/oauth2-proxy/manifests/commit/9ef089b45922650840cdf4c44842c7a2e9691151#diff-d2ec12fa131797b240c1ae945cb0fb458d289bca1759b6839a219928860baad2

There was already some discussion on how to implement this: https://github.com/oauth2-proxy/manifests/pull/41

**Comment by pierluigilenoci** [comment]
@czunker feel free to do a PR to correct the problem.
