### ISSUE TITLE
How to use this HELM chart to set other oauth2 Provider?

### ISSUE THREAD

**Issue by latituder** [oauth2-proxy/manifests#54]
It seems this HELM chart use google as the default oauth2 provider.
Would it possible to specific other oauth2 provider in the values.yaml?
e.g: to use generic OIDC provider?

**Comment by pierluigilenoci** [comment]
@latituder you need to configure the proper provider with `--provider` option:
Ref: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/
Ref: https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/

The configuration must be passed to the chart with the `extraArgs`:
Ref: https://github.com/oauth2-proxy/manifests/blob/main/helm/oauth2-proxy/values.yaml#L45

**Comment by latituder** [comment]
THANK YOU!
the `extraArgs`  options resolved the question.

```
        --set-string extraArgs.provider='oidc' \
        --set-string extraArgs.provider-display-name=${OAUTH_ISSUER_NAME} \
        --set-string extraArgs.redirect-url="https://${APP_INGRESS_FULL_URL}/oauth2/callback" \
        --set-string extraArgs.oidc-issuer-url=${OAUTH_ISSUER_IAS_URL} \
```

**Comment by eltharynd** [comment]
This doesn't seem to be working anymore and I'm having the same issue...
Where is the correct place to add my provider options?
