### ISSUE TITLE
Anyone got redis working?

### ISSUE THREAD

**Issue by holmesb** [oauth2-proxy/manifests#59]
According to my testing, redis doesn't work using this helm chart because oauth2-proxy pod fails to start due to error:

```
2021/09/22 17:08:46] [main.go:54] invalid configuration:
  unable to set a redis initialization key: NOAUTH Authentication required.
```

Fixed by manually editing the deployment and adding [command-line option](https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#command-line-options): `--redis-password <your redis password>`.  This chart currently does not support this switch.

**Comment by morganchristiansson** [comment]
So you could just specify the following values.yaml

```
extraArgs:
  redis-password: <your redis password>
```

**Comment by nbraun-wolf** [comment]
@morganchristiansson  If we have to set the password like this, what is the purpose of the value `sessionStorage.redis.password` ?

**Comment by nbraun-wolf** [comment]
I figured out that its because of the old version of the redis chart. See #26.

With 10.6.0 we have to use `redis.password`.
