### ISSUE TITLE
Add support for custom Container SecurityContext

### ISSUE THREAD

**Issue by rlacko58** [oauth2-proxy/manifests#67]
Problem: 
Currently you can't define a custom `securityContext` for a container.
This is a problem because you can't set for example `allowPrivilegeEscalation` or `capabilities` to the pod. ([Documentation](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/))
https://github.com/oauth2-proxy/manifests/blob/7089e0ec39ed44dc27e0df25c23dd15d1b6a06b9/helm/oauth2-proxy/templates/deployment.yaml#L191-L194

Solution:
Backwards compatible:
```yaml
{{- if .Values.securityContext.enabled }}
{{- $securityContext := unset .Values.securityContext "enabled" }}
        securityContext:
          {{- toYaml $securityContext | nindent 10 }}
{{- end }}
```

Or if we don't want backwards compatibility do the same as with podSecurityContext:
https://github.com/oauth2-proxy/manifests/blob/7089e0ec39ed44dc27e0df25c23dd15d1b6a06b9/helm/oauth2-proxy/templates/deployment.yaml#L37-L40

Which do you prefer? I could submit a pull request after discussion

**Comment by pierluigilenoci** [comment]
@rlacko58 would you like to do a PR to solve?
