### ISSUE TITLE
helm chart configuration option naming convention mismatch 

### ISSUE THREAD

**Issue by chuegel** [oauth2-proxy/manifests#80]
Hi, 
first thanks for providing the helm chart for this awesome project. 
I noticed that the latest helm chart does not reflect the naming convention of the official configuration options

see:  https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/

for example:

--whitelist-domain =! --whitelist_domains
--email-domain =! --email_domains
etc

## Expected Behavior
To be able to use same naming convection as described in the official documentation

## Current Behavior

see above

## Your Environment
RKE k8s cluster
helm chart version 5.4.0
oauth2-proxy version 7.2.1

**Comment by pierluigilenoci** [comment]
@chuegel the options you use as an example are absolutely legitimate.

The documentation explicitly says:
`Every command-line argument can be specified in a config file by replacing hyphens (-) with underscores (_). If the argument can be specified multiple times, the config option should be plural (trailing s).`

For example, when you need to specify more than one email domain there are two ways:
* like args `--email-domain ".example.com" --email-domain ".example2.com"`
* inside the config file `email_domains = [" .example.com "" .example2.com "]`

I hope this makes it clearer.

If not, this repo is still not the right place to raise the issue.
Here is only the chart, your observations concern the software itself. 
Ref: https://github.com/oauth2-proxy/oauth2-proxy
