### ISSUE TITLE
incorrect connectionUrl type

### ISSUE THREAD

**Issue by artemiyokulov** [oauth2-proxy/manifests#96]
In template expecting string https://github.com/oauth2-proxy/manifests/blob/oauth2-proxy-6.2.0/helm/oauth2-proxy/templates/deployment.yaml#L142

but in docs (https://github.com/oauth2-proxy/manifests/tree/main/helm/oauth2-proxy) descibed as a list

**Comment by pierluigilenoci** [comment]
@artemiyokulov would you like to open a PR to solve it?

**Comment by pierluigilenoci** [comment]
@artemiyokulov what about this?

**Comment by pierluigilenoci** [comment]
@artemiyokulov any update on this?

**Comment by pierluigilenoci** [comment]
@artemiyokulov would you like to open a PR for this?

**Comment by pierluigilenoci** [comment]
@desaintmartin, could you please take a look?

**Comment by pierluigilenoci** [comment]
@artemiyokulov This parameter is passed to the OAuth2-Proxy ad environment variable, so it should be a well-formed string interpreted as an array by the software.

**Comment by pierluigilenoci** [comment]
I'm closing the issue as there is no way to pass this information as an environment variable.

Information about this can be found here:
* https://pkg.go.dev/github.com/msepp/oauth2_proxy/v4/pkg/apis/options
* https://stackoverflow.com/questions/31352317/how-to-pass-a-list-as-an-environment-variable

Note: In case I'm wrong, anyone who wants to propose an alternative solution is welcome to open a PR.
