### ISSUE TITLE
Question: Can we injectResponseHeaders for each upstream with alpha-config?

### ISSUE THREAD

**Issue by lnvn** [oauth2-proxy/manifests#98]
I have a question that: can we injectResponseHeaders for each upstream like NGINX (location).

## Expected Behavior

    injectResponseHeaders:            #for all upstream service
      - name: xxx
        values:
          - value: xxx
    upstreamConfig:
      upstreams:
        - flushInterval: 1s
          id: /
          passHostHeader: true
          path: /
          proxyWebSockets: true
          uri: http://service1:8080
        - flushInterval: 1s
          id: /service2/
          passHostHeader: true
          path: /service2/
          proxyWebSockets: true
          injectResponseHeaders:            #Expected Behavior
          - name: yyy
             values:
             - value: yyy
          uri: http://service2:8081/service2/

## Current Behavior

    injectResponseHeaders:
      - name: xxx
        values:
          - value: xxx
       - name: yyy
          values:
          - value: yyy
    upstreamConfig:
      upstreams:
        - flushInterval: 1s
          id: /
          passHostHeader: true
          path: /
          proxyWebSockets: true
          uri: http://service1:8080
        - flushInterval: 1s
          id: /service2/
          passHostHeader: true
          path: /service2/
          proxyWebSockets: true
          uri: http://service2:8081/service2/

## Context

I want some header only affect to one service.

## Your Environment
- Version used: Helm chart version: 6.x.x

Thanks!

**Comment by pierluigilenoci** [comment]
@newhorizs feel free to open a PR for that

**Comment by pierluigilenoci** [comment]
@newhorizs any update on this?

**Comment by newhorizs** [comment]
@pierluigilenoci Sorry, I still don't have any further investigation on this.

**Comment by pierluigilenoci** [comment]
@iim5 would you like to open a PR to solve the problem?

**Comment by pierluigilenoci** [comment]
@lnvn, would you like to open a PR to solve the problem?

**Comment by lnvn** [comment]
Hi @pierluigilenoci, I have re-investigate this issue,  It seem that this option is not allowed on alpha config, so we can not do it.
I will close this ticket.
Thanks!
